# Generated by Django 4.0.3 on 2022-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexcard',
            name='age',
        ),
        migrations.RemoveField(
            model_name='indexcard',
            name='name',
        ),
        migrations.AddField(
            model_name='indexcard',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='professor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='venue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indexcard',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
