# Generated by Django 4.0.3 on 2022-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0002_remove_indexcard_age_remove_indexcard_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcard',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='sched',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='start',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
