# Generated by Django 4.0.3 on 2022-03-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0004_alter_indexcard_end_alter_indexcard_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcard',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='indexcard',
            name='start',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
