# Generated by Django 4.0.3 on 2022-03-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0005_alter_indexcard_end_alter_indexcard_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexcard',
            name='end',
        ),
        migrations.RemoveField(
            model_name='indexcard',
            name='start',
        ),
    ]
