# Generated by Django 4.0.3 on 2022-03-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0007_indexcard_end_indexcard_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcard',
            name='copypaste',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
