# Generated by Django 4.0 on 2022-03-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0008_indexcard_copypaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Class Code')),
            ],
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20, null=True)),
                ('sched', models.CharField(max_length=10, null=True)),
                ('start', models.TimeField(null=True)),
                ('end', models.TimeField(null=True)),
                ('venue', models.CharField(max_length=20, null=True)),
                ('professor', models.CharField(max_length=50, null=True)),
                ('copypaste', models.CharField(max_length=1000, null=True)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enlistmentbuddyapp.classcode', verbose_name='Class Code')),
            ],
        ),
    ]
