# Generated by Django 4.0.3 on 2022-03-29 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0009_classcode_classmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enlistmentbuddyapp.classcode', verbose_name='Class Code'),
        ),
    ]
