# Generated by Django 4.0.3 on 2022-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0010_alter_classmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='copypaste',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
