# Generated by Django 4.0.3 on 2022-04-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlistmentbuddyapp', '0011_alter_classmodel_copypaste'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='islocked',
            field=models.BooleanField(default=False),
        ),
    ]
